name: @name@
author: @author@
authors: [Korne127, LeStegii, Almighty-Satan]
version: @version@
softdepend: [PlaceholderAPI, LabyModAPI, TelegramPlugin, PermissionsEx, LabyModAPI]
loadbefore: [CuukyFrameWork, JDA]
api-version: 1.13
main: de.cuuky.varo.app.Main
website: VaroPlugin.de