name: ${name}
author: Cuuky
authors: [Korne127, LeStegii, Almighty-Satan]
version: ${version}
softdepend: [PlaceholderAPI, LabyModAPI, PermissionsEx, Multiverse-Core]
loadbefore: [CuukyFrameWork]
api-version: 1.13
main: de.varoplugin.varo.VaroJavaPlugin
website: VaroPlugin.de

commands:
  Test: