package de.cuuky.varo.entity.player.stats;

public enum KickResult {

	DEAD,
	NO_SESSIONS_LEFT,
	NO_PREPRODUCES_LEFT,
	NO_PROJECTUSER,
	NOT_IN_TIME,
	NO_TIME,
	BANNED,
	STRIKE_BAN,
	SERVER_NOT_PUBLISHED,
	ALLOW,
	SPECTATOR,
	MASS_RECORDING_JOIN,
	FINALE_JOIN,
	SERVER_FULL;

}
