name: VaroPlugin
authors: [Cuuky, Korne127, LeStegii, Almighty-Satan]
version: ${version}
# softdepend: [PlaceholderAPI, LuckPerms, PermissionsEx, Multiverse-Core, WorldEdit]
# loadbefore: [CuukyFrameWork]
api-version: 1.25.5
main: de.varoplugin.varo.Main
bootstrapper: de.varoplugin.varo.VaroBootstrap
loader: de.varoplugin.varo.VaroPluginLoader
website: VaroPlugin.de