Main:
  prefix: '&7[&3ODV&7] '
  projectname: ODV
  projectnameColorcode: '&3'
  supportPluginAds: false
  scoreboard: true
  nametags: true
  tablist: true
  playTime: -1
  dailyBackups: false
  unregisteredPlayerJoin: true
  resetSessionHour: 1
OfflineVillager:
  enableOfflineVillager: false
  noSatiationRegenerate: false
Backpacks:
  backpackPlayerEnabled: false
  backpackPlayerSize: 54
  backpackPlayerDropOnDeath: true
  backpackTeamEnabled: false
  backpackTeamSize: 54
  backpackTeamDropOnDeath: true
Protections:
  joinProtectionTime: 10
  canWalkOnJoinProtection: false
  startperiodProtectiontime: -1
Serverlist:
  changeMotd: true
  fakeMaxSlots: -1
Strike:
  postAtResetHour: false
  banOnPostHours: -1
  banAtPost: true
Teams:
  friendlyFire: true
  teamPlaceSpawn: -1
  triggerForGlobal: false
  chatTrigger: '#'
  teamRequests: true
  teamRequestExpiretime: 30
  teamRequestMaxTeamMembers: 2
  teamRequestMaxTeamnameLength: 10
JoinSystems:
  ignoreJoinSystemsAsOP: true
  sessionsPerDay: -1
  joinAfterHours: -1
  preProduceSessions: -1
  catchUpSessions: false
  onlyJoinBetweenHours: false
  onlyJoinBetweenHoursHour1: 14
  onlyJoinBetweenHoursHour2: 16
  kickAtServerClose: false
  massRecordingTime: 15
Death:
  deathSound: false
  kickDelayAfterDeath: -1
  stopServerOnWin: -1
  killerHealthAddOnKill: -1
  playerSpectateAfterDeath: false
  teamLifes: 1
  respawnProtection: 120
  addTeamLifesOnKill: -1
Finale:
  playerSpectateInFinale: true
  borderSizeInFinale: 300
  finaleProtectionTime: 30
World:
  blockDestroyLogger: true
  setAlwaysTime: 1000
  alwaysTimeUseAfterStart: false
  randomChestFillRadius: 30
  randomChestMaxItems: 5
  spawnProtectionRadius: 0
  setNameTagOverSpawn: true
  nametagSpawnHeight: 3
  blockUserPortals: true
Start:
  startCountdown: 30
  canMoveBeforeStart: false
  doRandomTeamAtStart: 2
  doSortAtStart: true
  removePlayersArentAtStart: true
  spawnTeleportAtLobbyPhase: true
  startAtPlayers: -1
Disconnect:
  maxDisconnectsPerSessions: 3
  strikeOnMaxDisconnect: false
  banAfterDisconnectMinutes: 10
  noDisconnectPing: 200
Combatlog:
  combatlogTime: 30
  strikeOnCombatlog: false
  killOnCombatlog: true
Border:
  deathBorderDecrease:
    enabled: false
    size: 25
    speed: 1
  minuteBorderDecrease:
    enabled: false
    minutes: 30
    size: 50
    speed: 5
  dayBorderDecrease:
    enabled: false
    days: 3
    size: 50
    speed: 5
  minBorderSize: 100
  showDistanceToBorder: false
  distanceToBorderRequired: -1
  borderDamage: 1
  outsideBorderSpawnTeleport: true
Chat:
  canChatBeforeStart: true
  chatCooldownInSeconds: 3
  chatCooldownIfStarted: false
Activity:
  noBloodlustDays: -1
  strikeOnBloodlust: false
  noActivityDays: -1
  strikeOnNoActivity: false
  postCoordsDays: -1
Report:
  enabled: true
  reportDelay: 30
  logReports: true
  reportStaffMember: true
YouTube:
  enabled: false
  setOwnLink: true
  videoIdentifier: ODV
Discord:
  discordBotEnabled: false
  botToken: ENTER TOKEN HERE
  eventChannelID: -1
  eventChannel:
    strike: -1
    joinLeave: -1
    win: -1
    info: -1
    kill: -1
    death: -1
    alert: -1
    youtube: -1
  serverGuildID: -1
  verifySystem: true
  verifySystemMySQL: false
  mysql_verify:
    mysql_host: HOST_HERE
    mysql_user: USER_HERE
    mysql_password: PASSWORD_HERE
    mysql_database: DATABASE_HERE
  registerChannelID: -1
  announcementChannelID: -1
  announcementPingRoleID: -1
  resultChannelID: -1
  addPokalOnWin: true
  setTeamAsGroup: false
  inviteLink: https://discord.gg/UPCZ9eX
  commandTrigger: '!varo '
  randomMessageColor: false
  gameState: 'ODV | Plugin by Cuuky - Contributors: Korne127'
Telegram:
  telegrambotEnabled: false
  botToken: ENTER TOKEN HERE
  eventChatId: -1
  videosChatId: -1
Autosetup:
  enabled: true
  border: 2000
  autostart:
    time:
      hour: 18
      minute: 0
  portal:
    width: 4
    height: 5
  lobby:
    schematic: plugins/Varo/schematics/lobby.schematic
    size: 25
    height: 10
  spawns:
    radius: 30
    amount: 40
    block:
      material: STONE_BRICK_SLAB
    sideblock:
      material: GRASS
Other:
  playerChestLimit: 2
  playerFurnaceLimit: -1
  noKickDistance: 30
  showTimeInActionbar: false
  disableLabyModFunctions: false
  kickLabyModPlayer: false
  onlyLabyModPlayer: false
  minimalSpectatorHeight: 70
  broadcastIntervalInSeconds: -1
  removeHitDelay: true
  allowTrolling: false
  debugOptions: true