name: Varo
author: Cuuky
authors: [Korne127, UeberallGebannt]
version: 4.5.1
softdepend: [CuukyFrameWork, JDA, LabyModAPI, TelegramPlugin, PermissionsEx, LabyModAPI]
api-version: 1.13
main: de.cuuky.varo.Main
website: VaroPlugin.de

commands:
  varo:
    aliases: [titan, uhc, odv, onedayvaro, suro]
    description: Hauptbefehl des Plugins
  Antixray:
    description: Schaltet einen Schutz vor X-Ray an und aus
  Broadcast:
    aliases: [bc]
    description: Sendet eine Nachricht an den Server
  ChatClear:
     aliases: [cc]
     description: Leert den Chat
  Day:
     description: Setzt die Tageszeit auf Tag
  Night:
     description: Setzt die Tageszeit auf Nacht
  Fly:
     description: Lässt dich oder einen Spieler fliegen
  Freeze:
     aliases: [nomove]
     description: Lässt einen Spieler einfrieren
  Gamemode:
     aliases: [gm]
     description: Setzt den Spielmodus von dir oder einem Spieler
  Heal:
     aliases: [feed]
     description: Heilt einen Spieler
  Info:
     aliases: [life]
     description: Zeigt Infos über einen Spieler
  Invsee:
     aliases: [inventorysee]
     description: Zeigt das Inventar eines anderen Spielers
  Ping:
     description: Zeigt den Ping von dir oder einem Spieler
  Speed:
     description: Setzt die Geschwindigkeit von dir oder einem Spieler
  Vanish:
     aliases: [v]
     description: Versteckt dich oder einen Spieler vor allen anderen
  Message:
     aliases: [msg]
     description: Schreibt einen Spieler eine Nachricht
  Reply:
     aliases: [r]
     description: Antwortet einem Spieler
  Mute:
     description: Mutet einen Spieler
  Protect:
     description: Beschützt Spieler vor Schaden
  Report:
     description: Reporte einen Spieler
  Unfly:
     description: Lässt dich oder einen Spieler nicht mehr fliegen
  Unfreeze:
     aliases: [move]
     description: Entfriert einen Spieler
  Unmute:
     description: Entmutet einen Spieler
  Usage:
     description: Zeigt die Nutzung des Servers
  Unprotect:
     description: Beendet die Beschützung vor Schaden von Spielern
  Border:
     aliases: [setborder]
     description: Zeigt Infos zur Border
  SetWorldspawn:
     description: Setzt die WorldBorder
  Spawn:
     description: Zeigt Distanz und Information zum Spawn
  Thunder:
     description: Wechselt zu Gewitter
  Rain:
     description: Wechselt zu Regen
  Sun:
     description: Wechselt zu schönem Wetter
  Countdown:
     description: Startet einen Countdown
  Performance:
     description: Verbessert die Performance
  Language:
     aliases: [lang, язык, 语言]
     description: Changes language of player